# Workflow name
name: 'Chromatic Deployment'

# Event for the workflow
on:
  push:
    branches: ['main', 'develop']

# List of jobs
jobs:
  test:
    # Operating System
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.16.1]

    # Job steps
    steps:
      - name: cache clean
        run: npm cache clean --force

      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: npm install -g yarn@4.0.1
      - name: Yarn Install
        run: yarn install

        #👇 Adds Chromatic as a step in the workflow
      - uses: chromaui/action@v1
        # Options required for Chromatic's GitHub Action
        with:
          #👇 Chromatic projectToken, see https://storybook.js.org/tutorials/intro-to-storybook/react/ko/deploy/ to obtain it
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
